# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ecc741818cd2ebdcc2b66ada47e32e2e76dae79d0dd9fe596ebf03765e0681cba13878e981c36a4b4854fe968572e6a49fb119b856932f90a88bcf01fc8bf86

test:
  secret_key_base: 0785ebe32ae76cc9e69ee2f6cbe74f70c91fa5ca74c06bff90d53f35c55528e8a6702dddd73b6d8b730d51396d01ecdd8fcb9b704c57994b9e795db1b1ab170e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
